---
- hosts: all
  vars:
    # Ensure you create a GSLT token for the game ID 581320
    gslt_token: "{{ lookup('env', 'GSLT_TOKEN') }}"

  roles:
    - role: kriansa/os-base
      hostname: sandstorm-srv
      open_ports:
        - 27131/udp
        - 27102/udp

  handlers:
    - name: restart sandstorm-auto-restarter
      become: true
      systemd: name=sandstorm-auto-restarter state=restarted enabled=true daemon_reload=true

    - name: restart sandstorm-auto-settings
      become: true
      systemd: name=sandstorm-auto-settings state=restarted enabled=true daemon_reload=true

    - name: restart sandstorm
      become: true
      systemd: name=sandstorm state=restarted enabled=true daemon_reload=true

  tasks:
    - name: install the required packages
      become: true
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - glibc.i686
          - libstdc++.i686
          - vim

    - name: add steam user
      become: true
      user: name=steam

    # In the future, we might use PolicyKit to handle system wide units for this user
    # See: https://serverfault.com/a/841150
    - name: enable sandstorm restart for steam user
      become: true
      lineinfile:
        path: /etc/sudoers.d/steam
        create: true
        line: "steam	ALL=(ALL)	NOPASSWD: /usr/local/bin/restart-server"

    - name: install rcon-cli
      become: true
      unarchive:
        src: https://github.com/itzg/rcon-cli/releases/download/1.4.4/rcon-cli_1.4.4_linux_amd64.tar.gz
        dest: /usr/local/bin
        creates: /usr/local/bin/rcon-cli
        remote_src: true
        exclude:
          - README.md
          - LICENSE

    - name: create /srv/sandstorm
      become: true
      file: path=/srv/sandstorm state=directory mode=0755 owner=steam group=steam

    - name: create steamcmd directory
      become: true
      become_user: steam
      file: path=/home/steam/steamcmd state=directory mode=0755

    - name: install steamcmd
      become: true
      become_user: steam
      unarchive:
        src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /home/steam/steamcmd
        creates: /home/steam/steamcmd/steamcmd.sh
        remote_src: true

    - name: upload server binaries
      notify: restart sandstorm
      become: true
      copy: src=files/app/bin/ dest=/usr/local/bin mode=0755

    - name: install sandstorm
      become: true
      become_user: steam
      command: /usr/local/bin/update-server
      args:
        creates: /srv/sandstorm/Insurgency

    - name: add tricks to the motd
      become: true
      copy:
        dest: /etc/motd
        content: |
          Sandstorm Server
          ================

          Quick commands:
            gprop - Show or edit a game property
            edit - Open the config.env using vim
            restart - Restarts the game daemon
            logs - Show and follow the logs
            players-count - List the amount of players connected

    - name: add shell aliases to the root user
      become: true
      blockinfile:
        path: /root/.bashrc
        block: |
          alias gprop=gameprop
          alias edit="vim /etc/sandstorm/config.env"
          alias restart="systemctl restart sandstorm"
          alias logs="journalctl -fu sandstorm"

    - name: add the extra auth ssh key
      become: true
      authorized_key:
        user: root
        comment: Additional authentication key
        key: "{{ lookup('file', 'id_rsa.pub') }}"

    - name: upload player-counter
      notify: restart sandstorm
      become: true
      copy: src=players-count dest=/usr/local/bin mode=0755

    - name: create /etc/sandstorm
      become: true
      file: path=/etc/sandstorm state=directory mode=0755

    - name: copy server config files
      notify: restart sandstorm
      become: true
      copy: src={{ item }} dest=/etc/sandstorm
      with_fileglob: files/app/etc/*.ini

    - name: copy the config.env
      become: true
      template: src=files/app/etc/config.env.j2 dest=/etc/sandstorm/config.env mode=0644

    - name: create {{ item }} service
      notify: restart {{ item }}
      become: true
      copy:
        src: files/{{ item }}.service
        dest: /etc/systemd/system/{{ item }}.service
        mode: 0644
      loop:
        - sandstorm
        - sandstorm-auto-restarter
        - sandstorm-auto-settings
