---
- hosts: all
  vars:
    server_name: "ZGO:US | NO MERCY, Security, Co-op Challenges"
    # For a list of maps & scenarios, see:
    # https://docs.google.com/document/d/1GDLg5p9jjeIya7EgBk0ibzDtDlyQ-U_jpspOzby-JmM/edit
    # The gamemode can be either Checkpoint or CheckpointHardcore
    initial_map: Sinjar?Scenario=Scenario_Hillside_Checkpoint_Security?Game=Checkpoint
    mapcycle: MapCycle-Coop-Security
    # Ensure you create a GSLT token for the game ID 581320
    gslt_token: "{{ lookup('env', 'GSLT_TOKEN') }}"

  roles:
    - role: kriansa/os-base
      hostname: sandstorm-srv
      open_ports:
        - 27131/udp
        - 27102/udp

  handlers:
    - name: restart auto-reboot service
      become: true
      systemd: name=sandstorm-auto-restarter state=restarted enabled=true daemon_reload=true

    - name: restart auto-settings service
      become: true
      systemd: name=sandstorm-auto-settings state=restarted enabled=true daemon_reload=true

    - name: restart sandstorm
      become: true
      systemd: name=sandstorm state=restarted enabled=true daemon_reload=true

  tasks:
    - name: install the required packages
      become: true
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - glibc.i686
          - libstdc++.i686

    - name: add steam user
      become: true
      user: name=steam

    # In the future, we might use PolicyKit to handle system wide units for this user
    # See: https://serverfault.com/a/841150
    - name: enable sandstorm restart for steam user
      become: true
      lineinfile:
        path: /etc/sudoers.d/steam
        create: true
        line: "steam	ALL=(ALL)	NOPASSWD: /usr/local/bin/restart-server"

    - name: install rcon-cli
      become: true
      unarchive:
        src: https://github.com/itzg/rcon-cli/releases/download/1.4.4/rcon-cli_1.4.4_linux_amd64.tar.gz
        dest: /usr/local/bin
        creates: /usr/local/bin/rcon-cli
        remote_src: true
        exclude:
          - README.md
          - LICENSE

    - name: create /srv/sandstorm
      become: true
      file: path=/srv/sandstorm state=directory mode=0755 owner=steam group=steam

    - name: create steamcmd directory
      become: true
      become_user: steam
      file: path=/home/steam/steamcmd state=directory mode=0755

    - name: install steamcmd
      become: true
      become_user: steam
      unarchive:
        src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /home/steam/steamcmd
        creates: /home/steam/steamcmd/steamcmd.sh
        remote_src: true

    - name: upload server binaries
      notify: restart sandstorm
      become: true
      copy: src=files/app/bin/ dest=/usr/local/bin mode=0755

    - name: add gprop shell alias to root user
      become: true
      blockinfile:
        path: /root/.bashrc
        block: |
          alias gprop=gameprop
          edit="vi /srv/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini"
          restart="systemctl restart sandstorm"
          logs="journalctl -fu sandstorm"

    - name: upload player-counter
      notify: restart sandstorm
      become: true
      copy: src=files/app/lib/player-counter/build/players-count dest=/usr/local/bin mode=0755

    - name: install sandstorm
      become: true
      become_user: steam
      command: /usr/local/bin/update-server
      args:
        creates: /srv/sandstorm/Insurgency

    - name: copy server files
      notify: restart sandstorm
      become: true
      become_user: steam
      copy: src=files/app/src/ dest=/srv/sandstorm

    - name: create systemd service
      notify: restart sandstorm
      become: true
      template: src=templates/systemd-service dest=/etc/systemd/system/sandstorm.service mode=0644

    - name: create auto-restarter service
      notify: restart auto-reboot service
      become: true
      copy:
        src: files/sandstorm-auto-restarter.service
        dest: /etc/systemd/system/sandstorm-auto-restarter.service
        mode: 0644

    - name: create auto-settings service
      notify: restart auto-settings service
      become: true
      copy:
        src: files/sandstorm-auto-settings.service
        dest: /etc/systemd/system/sandstorm-auto-settings.service
        mode: 0644
