---
- hosts: all
  vars:
    server_name: "🔫 ZG: Checkpoint | Hard | 16 Bots | Unlimited Supply"

  handlers:
    - name: restart sandstorm
      become: true
      systemd:
        name: sandstorm
        state: restarted
        enabled: true
        daemon_reload: true

    - name: reboot
      become: true
      reboot:

    - name: restart ssh
      become: true
      systemd: name=sshd state=restarted

    - name: restart yum-cron
      become: true
      systemd: name=yum-cron state=restarted

  tasks:
    - name: set hostname
      become: true
      hostname: 
        name: sandstorm-srv

    - name: install the required packages
      become: true
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - glibc.i686
          - libstdc++.i686
          - yum-cron
          - htop

    - name: upgrade all packages
      become: true
      yum:
        name: '*'
        state: latest
        exclude: kernel

    - name: upgrade the kernel
      notify: reboot
      become: true
      yum: name=kernel state=latest

    - name: enable game ports on firewalld
      become: true
      when: ansible_distribution == 'CentOS'
      firewalld:
        port: "{{ item }}/udp"
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
        - 27131
        - 27102

    - name: configure yum-cron
      become: true
      notify: restart yum-cron
      lineinfile: 
        path: /etc/yum/yum-cron.conf
        regexp: '^apply_updates'
        line: apply_updates = yes

    - name: disable password SSH auth
      become: true
      notify: restart ssh
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: PasswordAuthentication no

    - name: add steam user
      become: true
      user: name=steam

    - name: enable sandstorm restart for steam user
      become: true
      lineinfile:
        path: /etc/sudoers.d/steam
        line: "steam	ALL=(ALL)	NOPASSWD: /usr/bin/systemctl restart sandstorm"

    - name: install rcon-cli
      become: true
      unarchive:
        src: https://github.com/itzg/rcon-cli/releases/download/1.4.4/rcon-cli_1.4.4_linux_amd64.tar.gz
        dest: /usr/local/bin
        creates: /usr/local/bin/rcon-cli
        remote_src: true
        exclude:
          - README.md
          - LICENSE

    - name: create /srv/sandstorm
      become: true
      file: path=/srv/sandstorm state=directory mode=0755 owner=steam group=steam

    - name: create steamcmd directory
      become: true
      become_user: steam
      file: path=/home/steam/steamcmd state=directory mode=0755

    - name: install steamcmd
      become: true
      become_user: steam
      unarchive:
        src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /home/steam/steamcmd
        creates: /home/steam/steamcmd/steamcmd.sh
        remote_src: true

    - name: upload server binaries
      notify: restart sandstorm
      become: true
      copy: src=files/server-bin/ dest=/usr/local/bin mode=0755

    - name: install sandstorm
      become: true
      become_user: steam
      command: update-server
      args:
        creates: /srv/sandstorm/Insurgency

    - name: create systemd service
      notify: restart sandstorm
      become: true
      template: src=templates/systemd-service dest=/etc/systemd/system/sandstorm.service mode=0644

    - name: enable restarts every 6 hours
      become: true
      become_user: steam
      cron:
        name: restarts sandstorm every 6 hours
        minute: 0
        hour: "3,9,15,21"
        job: restart-server

    - name: copy server files
      notify: restart sandstorm
      become: true
      become_user: steam
      copy: src=files/server-src/ dest=/srv/sandstorm
