---
- hosts: all
  vars:
    server_name: "🔫 | ZG | 24 Bots | Security | Respawn Tkts"
    # For a list of maps & scenarios, see: 
    # https://docs.google.com/document/d/1GDLg5p9jjeIya7EgBk0ibzDtDlyQ-U_jpspOzby-JmM/edit
    # The gamemode can be either Checkpoint or CheckpointHardcore
    initial_map: Ministry?Scenario=Scenario_Ministry_Checkpoint_Security?Game=Checkpoint
    mapcycle: MapCycle-Coop-Security
    gslt_token: "{{ lookup('env', 'GSLT_TOKEN') }}"

  roles:
    - role: kriansa/os-base
      hostname: sandstorm-srv
      open_ports:
        - 27131/udp
        - 27102/udp

  handlers:
    - name: restart sandstorm
      become: true
      systemd:
        name: sandstorm
        state: restarted
        enabled: true
        daemon_reload: true

  tasks:
    - name: install the required packages
      become: true
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - glibc.i686
          - libstdc++.i686

    - name: add steam user
      become: true
      user: name=steam

    # In the future, we might use PolicyKit to handle system wide units for this user
    # See: https://serverfault.com/a/841150
    - name: enable sandstorm restart for steam user
      become: true
      lineinfile:
        path: /etc/sudoers.d/steam
        create: true
        line: "steam	ALL=(ALL)	NOPASSWD: /usr/local/bin/restart-server"

    - name: install rcon-cli
      become: true
      unarchive:
        src: https://github.com/itzg/rcon-cli/releases/download/1.4.4/rcon-cli_1.4.4_linux_amd64.tar.gz
        dest: /usr/local/bin
        creates: /usr/local/bin/rcon-cli
        remote_src: true
        exclude:
          - README.md
          - LICENSE

    - name: create /srv/sandstorm
      become: true
      file: path=/srv/sandstorm state=directory mode=0755 owner=steam group=steam

    - name: create steamcmd directory
      become: true
      become_user: steam
      file: path=/home/steam/steamcmd state=directory mode=0755

    - name: install steamcmd
      become: true
      become_user: steam
      unarchive:
        src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /home/steam/steamcmd
        creates: /home/steam/steamcmd/steamcmd.sh
        remote_src: true

    - name: upload server binaries
      notify: restart sandstorm
      become: true
      copy: src=files/app/bin/ dest=/usr/local/bin mode=0755

    - name: install sandstorm
      become: true
      become_user: steam
      command: /usr/local/bin/update-server
      args:
        creates: /srv/sandstorm/Insurgency

    - name: create systemd service
      notify: restart sandstorm
      become: true
      template: src=templates/systemd-service dest=/etc/systemd/system/sandstorm.service mode=0644

    - name: create restart-server log file
      become: true
      file: path=/var/log/restart-server.log state=touch mode=0644 owner=steam group=steam

    - name: enable restarts every 6 hours
      become: true
      become_user: steam
      cron:
        name: restarts sandstorm every 6 hours
        minute: "0"
        hour: "3,9,15,21"
        job: sudo /usr/local/bin/restart-server >> /var/log/restart-server.log 2>&1

    - name: copy server files
      notify: restart sandstorm
      become: true
      become_user: steam
      copy: src=files/app/src/ dest=/srv/sandstorm
